execute:
  execute_notebooks: auto

exclude_patterns: ["*ipynb"]

# launch_buttons:
#   notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
#   jupyterhub_url: "http:127.0.0.1:9500"

repository:
  url: https://github.com/executablebooks/jupyter-book
  branch: master
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "http:127.0.0.1:9500"

title: "HPC_EDU project"
